#!/usr/bin/env zsh

STOW_FOLDERS="ghostty,bin,git,nvim,nvim-2025,tmux,zsh,starship,aerospace,yazi"

DOT_FILES=$HOME/.dotfiles

pushd $DOT_FILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd


