#!/usr/bin/env zsh

STOW_FOLDERS="alacritty,ghostty,bin,git,nvim,nvim-2025,tmux,zsh,spaceship,aerospace,yazi,starship,ripgrep"

DOT_FILES=$HOME/.dotfiles

pushd $DOT_FILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "Removing $folder"
    stow -D $folder
done
popd
